✨ (API + Frontend) Added dynamic hour functionality to Au Pair Costs Page
COS301-SE-2022/The-Au-Pair pull request #131
Opened 2022-06-08 18:08 UTC by ricecakesreece

2022-06-08 18:16 UTC, Ruben-Brits requested changes
no Testing?

2022-06-09 05:09 UTC, d-azmanov commented on Server/src/main/java/Database/TheAuPair/Services/hoursLoggedService.java
>        String [] te = hourLog.getTimeEnd().split(":");
variables "ts" and "te" could be a bit more descriptive - just make them timeStart and timeEnd

2022-06-09 05:12 UTC, d-azmanov approved these changes
Just remember to stick to camel-case, we don't want to have infer what variables mean by the function calls , just type them out instead of abbreviations

2022-06-09 05:49 UTC, PxttytheThxtty approved these changes

2022-06-09 07:47 UTC, Ruben-Brits approved these changes

2022-06-09 07:47 UTC, merged