🩹(FIX) : Updated children's aupair field when hiring and terminating
COS301-SE-2022/The-Au-Pair pull request #265
Opened 2022-08-20 09:52 UTC by PxttytheThxtty

2022-08-20 15:02 UTC, priyo5 approved these changes

2022-08-21 13:27 UTC, ricecakesreece commented on libs/hire-requests/feature/src/lib/hire-requests.component.ts
> +  async getChildrenDetails(parent : string)
Rename function to be more descriptive e.g "setChildrenAuPair"

2022-08-21 13:27 UTC, ricecakesreece commented on libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
> + async getChildrenDetails()
Rename function to be more descriptive e.g "removeChildrenAuPair"

2022-08-21 16:09 UTC, Ruben-Brits submitted a review, later dismissed

2022-08-26 08:09 UTC, Ruben-Brits requested changes

2022-08-26 08:09 UTC, Ruben-Brits commented on libs/au-pair-dashboard/feature/src/lib/au-pair-dashboard.component.ts
> +    console.log(daysBetweenDates);
remove console logs please

2022-08-26 08:09 UTC, Ruben-Brits commented on libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
> +      console.log("HUH");
console log

2022-08-26 08:09 UTC, Ruben-Brits commented on libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
> +        console.log("NUMBER 1");
console log

2022-08-26 08:09 UTC, Ruben-Brits commented on libs/edit-au-pair-profile/feature/src/lib/edit-au-pair-profile.component.ts
> +        console.log("NUMBER 2");
just check logs please <3

2022-08-26 08:09 UTC, Ruben-Brits commented on libs/parent-dashboard/feature/src/lib/parent-dashboard.ts
> +    console.log("HERE");
console and empty lines

2022-08-27 13:49 UTC, d-azmanov approved these changes

2022-08-28 11:09 UTC, Ruben-Brits approved these changes

2022-08-28 13:26 UTC, merged