✅👔Registration and Login Tests + Login Check for ban
COS301-SE-2022/The-Au-Pair pull request #267
Opened 2022-08-22 20:49 UTC by ricecakesreece

2022-08-23 07:25 UTC, Ruben-Brits requested changes

2022-08-23 07:25 UTC, Ruben-Brits commented on libs/login/feature/src/lib/login.component.spec.ts
> +  login(email: string, password: string) {
remove unused variables

2022-08-23 07:25 UTC, Ruben-Brits commented on libs/register/feature/src/lib/register.component.spec.ts
> +  get(url: string) {
url defined but never used

2022-08-24 07:37 UTC, PxttytheThxtty approved these changes

2022-08-24 09:20 UTC, Ruben-Brits approved these changes

2022-08-24 09:20 UTC, merged