💄👽️(UI+API) Report Button for users
COS301-SE-2022/The-Au-Pair pull request #302
Opened 2022-09-07 11:23 UTC by ricecakesreece

Added report buttons, changed API names to better suit all users, added testing for multiple report related pages.

2022-09-09 14:18 UTC, Ruben-Brits requested changes

2022-09-09 14:18 UTC, Ruben-Brits commented on libs/au-pair-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.ts
> +
empty line

2022-09-09 14:18 UTC, Ruben-Brits commented on libs/parent-dashboard/feature/src/lib/parent-dashboard.component.spec.ts
> +});
newline

2022-09-09 14:18 UTC, Ruben-Brits commented on libs/parent-dashboard/feature/src/lib/user-report-modal/user-report-modal.component.ts
> +
empty line

2022-09-10 06:16 UTC, PxttytheThxtty submitted a review, later dismissed

2022-09-10 08:15 UTC, Ruben-Brits submitted a review, later dismissed

2022-09-10 08:15 UTC, Ruben-Brits commented
Please sort out merge conflict

2022-09-10 10:12 UTC, priyo5 approved these changes

2022-09-12 16:41 UTC, priyo5 approved these changes

2022-09-12 16:58 UTC, Ruben-Brits approved these changes

2022-09-12 17:08 UTC, merged