👽️🐛(API + Bugs) Changed Pie Graph to update with new costs and fixed total costs
COS301-SE-2022/The-Au-Pair pull request #361
Opened 2022-09-26 07:53 UTC by ricecakesreece

2022-09-26 07:59 UTC, d-azmanov submitted a review, later dismissed

2022-09-26 16:59 UTC, d-azmanov approved these changes

2022-09-26 17:47 UTC, PxttytheThxtty submitted a review, later dismissed

2022-09-27 19:31 UTC, priyo5 approved these changes

2022-09-28 08:13 UTC, Ruben-Brits requested changes

2022-09-28 08:13 UTC, Ruben-Brits commented on Server/src/main/java/Database/TheAuPair/Controllers/UserCostsController.java
> +  @PostMapping("/getTotalMonthCostsForOvertime")
```suggestion
  @PostMapping("/api/getTotalMonthCostsForOvertime")
```

2022-09-28 08:13 UTC, Ruben-Brits commented on Server/src/main/java/Database/TheAuPair/Controllers/UserCostsController.java
> +  @PostMapping("/getTotalMonthCostsForOther")
```suggestion
  @PostMapping("/api/getTotalMonthCostsForOther")
```

2022-09-28 08:24 UTC, Ruben-Brits approved these changes

2022-09-28 08:27 UTC, d-azmanov approved these changes

2022-09-28 08:28 UTC, merged